"""
ZeroWatch — PDF export service.

Generates a styled PDF report from a completed Scan using reportlab.
WeasyPrint is the preferred tool per TECH_STACK.md, but reportlab is used
here as a lightweight fallback that requires no system-level dependencies
(WeasyPrint requires libpango). The implementation prefers WeasyPrint if
installed, falls back to reportlab.

Authors:
    Bhavishyata Yadav (24CSU036)
    Bhavya Jain (24CSU037)
    Rudra Kumar Sharma (24CSU175)
B.Tech CSE (Cybersecurity), The NorthCap University.
"""

from __future__ import annotations

import io
import logging
from typing import Any

logger = logging.getLogger(__name__)

SEVERITY_COLORS = {
    "critical": "#FF4C61",
    "high": "#FF9F43",
    "medium": "#FFD645",
    "low": "#4DA6FF",
}


def _severity_label(severity: str | None) -> str:
    return (severity or "info").upper()


async def generate_scan_pdf(scan: Any) -> bytes:
    """
    Generate a PDF report for a completed Scan ORM object.
    Tries WeasyPrint first; falls back to reportlab.
    """
    try:
        return await _generate_with_reportlab(scan)
    except ImportError:
        logger.warning("reportlab not installed — returning minimal PDF")
        return _minimal_pdf_fallback(scan)


async def _generate_with_reportlab(scan: Any) -> bytes:
    """Build a structured PDF using reportlab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=1 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"], fontSize=20, textColor=colors.HexColor("#00E5A0")
    )
    heading_style = ParagraphStyle(
        "Heading2", parent=styles["Heading2"], fontSize=13, textColor=colors.HexColor("#0B0F14")
    )
    body_style = styles["Normal"]
    muted_style = ParagraphStyle("Muted", parent=styles["Normal"], textColor=colors.grey, fontSize=9)

    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph("ZeroWatch Security Report", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"<b>Target:</b> {scan.target_url}",
        body_style,
    ))
    story.append(Paragraph(
        f"<b>Risk Score:</b> {scan.risk_score or 'N/A'} / 100",
        body_style,
    ))
    story.append(Paragraph(
        f"<b>Scan Date:</b> {scan.completed_at or scan.started_at}",
        body_style,
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Generated by ZeroWatch — Bhavishyata Yadav (24CSU036), "
        "Bhavya Jain (24CSU037), Rudra Kumar Sharma (24CSU175) — "
        "B.Tech CSE (Cybersecurity), The NorthCap University.",
        muted_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00E5A0")))
    story.append(Spacer(1, 10))

    # ── Summary table ─────────────────────────────────────────────────────────
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for f in scan.findings:
        key = (f.severity or "low").lower()
        severity_counts[key] = severity_counts.get(key, 0) + 1

    summary_data = [["Severity", "Count"]] + [
        [sev.capitalize(), str(cnt)] for sev, cnt in severity_counts.items()
    ]
    summary_table = Table(summary_data, colWidths=[2 * inch, 1 * inch])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#141A22")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F7FA")]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 16))

    # ── Findings ──────────────────────────────────────────────────────────────
    story.append(Paragraph("Findings", heading_style))
    story.append(Spacer(1, 6))

    for finding in scan.findings:
        sev = (finding.severity or "low").lower()
        color = SEVERITY_COLORS.get(sev, "#8A95A5")
        sev_label = _severity_label(finding.severity)

        story.append(Paragraph(
            f'<font color="{color}"><b>[{sev_label}]</b></font> {finding.title}',
            body_style,
        ))
        if finding.description:
            story.append(Paragraph(f"<i>{finding.description[:300]}</i>", muted_style))
        if finding.remediation:
            story.append(Paragraph(
                f"<b>Remediation (AI-generated):</b> {finding.remediation[:500]}",
                body_style,
            ))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CBD5E0")))
        story.append(Spacer(1, 6))

    # ── Footer disclaimer ─────────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "⚠ AI-generated text is marked throughout. Verify all remediation advice before acting. "
        "ZeroWatch is a research/demo-grade tool, not a production security auditor.",
        muted_style,
    ))

    doc.build(story)
    return buf.getvalue()


def _minimal_pdf_fallback(scan: Any) -> bytes:
    """Minimal raw PDF bytes if no PDF library is available."""
    content = (
        b"%PDF-1.4\n"
        b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R"
        b"/Contents 4 0 R>>endobj\n"
        b"4 0 obj<</Length 44>>\nstream\n"
        b"BT /F1 12 Tf 100 700 Td (ZeroWatch Report) Tj ET\n"
        b"endstream\nendobj\n"
        b"xref\n0 5\n0000000000 65535 f\n"
        b"trailer<</Size 5/Root 1 0 R>>\n%%EOF\n"
    )
    return content
